const DB='MAGHRABY_PRO_V3',VER=3;
const stores=['products','sales','repairs','cash','expenses','purchases','customers','staff','invoices','days','audit','settings'];
let db,state={page:'dashboard',cat:'',cart:[],discount:0,cartNote:'',saleCustomer:'',lastInvoice:null};
const NAV=[
['dashboard','⌂','لوحة التحكم'],['sale','🛒','المبيعات والكاشير'],['repair','🔧','الصيانة والمتابعة'],
['inventory','📦','المخزون والمنتجات'],['purchases','🛍️','المشتريات والتوريد'],['customers','👥','العملاء'],
['cash','💰','الخزنة والحركات'],['expenses','💸','مصروفات المحل'],['staff','👨‍🔧','الفنيون والسلف'],
['needs','📋','الاحتياجات'],['reports','📊','الربح والتقارير'],['invoices','🧾','الفواتير'],['settings','⚙','الإعدادات']
];
const seed=[
{id:'ps5',name:'PS5 Disc',cat:'أجهزة',emoji:'🎮',price:25000,cost:21000,stock:2,min:1},
{id:'ps5d',name:'PS5 Digital',cat:'أجهزة',emoji:'🎮',price:23000,cost:19500,stock:1,min:1},
{id:'ps4',name:'PS4 Slim',cat:'أجهزة',emoji:'🎮',price:9000,cost:7500,stock:3,min:1},
{id:'ds5',name:'DualSense',cat:'دراعات',emoji:'🕹️',price:3400,cost:2800,stock:5,min:2},
{id:'ds4',name:'DualShock 4',cat:'دراعات',emoji:'🕹️',price:2400,cost:1900,stock:4,min:2},
{id:'hdmi',name:'HDMI Cable',cat:'إكسسوارات',emoji:'🔌',price:250,cost:120,stock:8,min:3},
{id:'bag',name:'شنطة جهاز',cat:'شنط',emoji:'🎒',price:700,cost:450,stock:3,min:1},
{id:'games',name:'تنزيل ألعاب',cat:'خدمات',emoji:'💾',price:300,cost:30,stock:999,min:0},
{id:'soft',name:'تحديث سوفتوير',cat:'خدمات',emoji:'⚙️',price:250,cost:20,stock:999,min:0},
{id:'mod',name:'تعديل جهاز',cat:'خدمات',emoji:'🛠️',price:600,cost:80,stock:999,min:0}
];
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),today=()=>now().slice(0,10);
const money=n=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(Number(n)||0)+' ج';
const val=id=>$(id)?.value?.trim()||'';
function req(s){return new Promise((res,rej)=>{let q=db.transaction(s).objectStore(s).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
function put(s,x){return new Promise((res,rej)=>{let q=db.transaction(s,'readwrite').objectStore(s).put(x);q.onsuccess=()=>res(x);q.onerror=()=>rej(q.error)})}
async function boot(){await new Promise((res,rej)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{db=r.result;stores.forEach(s=>{if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id'})})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)});if(!(await req('products')).length)for(const x of seed)await put('products',x);bind();clock();render()}
function bind(){$('menu').onclick=()=> $('sidebar').classList.toggle('open');$('backup').onclick=backup;$('closeToday').onclick=closeDay;document.addEventListener('click',e=>{let b=e.target.closest('[data-page]');if(b){state.page=b.dataset.page;state.cat='';render();$('sidebar').classList.remove('open')}})}
function clock(){setInterval(()=>{let d=new Date();$('date').textContent=d.toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('time').textContent=d.toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit',second:'2-digit'})},500)}
function nav(){ $('nav').innerHTML=NAV.map(n=>`<button class="nav-item ${state.page===n[0]?'active':''}" data-page="${n[0]}">${n[1]} ${n[2]}</button>`).join('');$('title').textContent=(NAV.find(n=>n[0]===state.page)||NAV[0])[2]}
async function render(){nav();let v=$('view');({dashboard,sale,repair,inventory,purchases,customers,cash,expenses,staff,needs,reports,invoices,settings}[state.page]||dashboard)(v)}
function stat(label,n,sub=''){return `<div class="card stat"><div class="label">${label}</div><div class="num">${typeof n==='number'?money(n):n}</div><div class="sub">${sub}</div></div>`}
async function dashboard(v){let [s,r,e,c,p]=await Promise.all([req('sales'),req('repairs'),req('expenses'),req('cash'),req('products')]),d=today(),sd=s.filter(x=>x.date.slice(0,10)===d),cd=c.filter(x=>x.date.slice(0,10)===d),ed=e.filter(x=>x.date.slice(0,10)===d),pending=r.filter(x=>x.status!=='تم التسليم'),low=p.filter(x=>x.stock<=x.min&&x.min>0),inc=cd.filter(x=>x.type==='in').reduce((a,x)=>a+x.amount,0),out=cd.filter(x=>x.type==='out').reduce((a,x)=>a+x.amount,0),cogs=sd.reduce((a,x)=>a+x.items.reduce((z,i)=>z+i.cost*i.qty,0),0),salesTotal=sd.reduce((a,x)=>a+x.total,0),profit=salesTotal-cogs-ed.reduce((a,x)=>a+x.amount,0);
v.innerHTML=`<div class="grid stats">${stat('مبيعات اليوم',salesTotal,'بعد الخصومات')}${stat('دخل الخزنة',inc,'كل حركات الداخل')}${stat('خرج الخزنة',out,'كل حركات الخارج')}${stat('صافي حركة الدرج',inc-out,'قبل العد الفعلي')}${stat('ربح تقريبي',profit,'مبيعات − تكلفة − مصروفات')}${stat('أجهزة معلقة',pending.length,'تحتاج متابعة')}</div>
<div class="section"><h2>مركز العمل</h2></div><div class="grid quick"><button data-page="sale">🛒<b>بيع جديد</b><small>سلة + خصم + ملاحظات + فاتورة</small></button><button data-page="repair">🔧<b>استلام صيانة</b><small>الجهاز والعطل والمدة والحالة</small></button><button data-page="cash">💵<b>حركة خزنة</b><small>دخل / خرج / سلفة / مصروف</small></button><button data-page="purchases">📦<b>شراء بضاعة</b><small>يزود المخزون ويحسب التكلفة</small></button><button data-page="reports">🔒<b>إقفال اليوم</b><small>عد الدرج واعرف الفرق</small></button></div>
<div class="grid two"><div><div class="section"><h2>⚠ يحتاج انتباه</h2></div><div class="card">${low.length?low.map(p=>`<div class="kpi"><span>📦 ${p.name}<small> — الموجود ${p.stock}</small></span><b class="negative">اطلب الآن</b></div>`).join(''):'<div class="empty">المخزون الأساسي جيد 🎉</div>'}</div></div><div><div class="section"><h2>🔧 الصيانة</h2></div><div class="card">${pending.slice(0,5).map(r=>`<div class="kpi"><span><b>${r.customer}</b> — ${r.device}<small> ${r.fault}</small></span><b class="negative">${Math.floor((Date.now()-new Date(r.date))/86400000)} يوم</b></div>`).join('')||'<div class="empty">لا توجد أجهزة معلقة</div>'}</div></div></div>`}
async function sale(v){let ps=await req('products'),cs=[...new Set(ps.map(p=>p.cat))],arr=ps.filter(p=>(!state.cat||p.cat===state.cat)&&p.name.toLowerCase().includes((state.q||'').toLowerCase()));v.innerHTML=`<div class="actions" style="margin-bottom:10px">${['الكل',...cs].map(c=>`<button class="btn ${(!state.cat&&c==='الكل')||state.cat===c?'primary':''}" onclick="state.cat='${c==='الكل'?'':c}';render()">${c}</button>`).join('')}</div><div class="grid two"><div class="card"><div class="search"><input placeholder="🔎 ابحث باسم المنتج..." value="${state.q||''}" oninput="state.q=this.value;render()"></div><div class="product-grid">${arr.map(p=>`<button class="product" onclick="add('${p.id}')"><div class="pic">${p.image?`<img src="${p.image}">`:p.emoji}</div><span class="stock">${p.stock>100?'خدمة':'مخزون '+p.stock}</span><div class="pi"><b>${p.name}</b><small>${p.cat}</small><strong>${money(p.price)}</strong></div></button>`).join('')}</div></div><div class="card cart"><h2 style="font-size:16px;margin:0 0 8px">🧺 السلة الذكية</h2><div class="cart-items">${cartHTML()}</div><div class="note"><label>ملاحظة البيع<textarea id="cartNote" oninput="state.cartNote=this.value" placeholder="مثال: عميل دائم / تسليم مع الشنطة / حالة الجهاز...">${state.cartNote}</textarea></label></div><div class="total"><div class="sum"><span>الإجمالي قبل الخصم</span><b>${money(sub())}</b></div><div class="sum"><span>الخصم</span><b>${money(state.discount)}</b></div><div class="sum grand"><span>المطلوب</span><span>${money(grand())}</span></div></div><div class="actions" style="margin-top:9px"><button class="btn orange" onclick="discount()">خصم</button><button class="btn" onclick="clearCart()">تفريغ</button><button class="btn primary" onclick="saveSale()">حفظ وطباعة</button></div></div></div>`}
function cartHTML(){if(!state.cart.length)return'<div class="empty">ابدأ باختيار منتج من اليمين</div>';return state.cart.map((x,i)=>`<div class="cart-row"><div><b>${x.name}</b><br><small>${money(x.price)} × ${x.qty}</small></div><div class="qty"><button onclick="changeQty(${i},-1)">−</button>${x.qty}<button onclick="changeQty(${i},1)">+</button></div><b>${money(x.price*x.qty)}</b></div>`).join('')}
function sub(){return state.cart.reduce((a,x)=>a+x.price*x.qty,0)}function grand(){return Math.max(0,sub()-state.discount)}
async function add(id){let p=(await req('products')).find(x=>x.id===id);if(!p)return;if(p.stock<=0)return toast('المنتج غير متوفر');let x=state.cart.find(x=>x.id===id);x?x.qty++:state.cart.push({id:p.id,name:p.name,price:p.price,cost:p.cost,qty:1});render()}
function changeQty(i,d){state.cart[i].qty+=d;if(state.cart[i].qty<1)state.cart.splice(i,1);render()}function clearCart(){state.cart=[];state.discount=0;state.cartNote='';render()}
function discount(){modal('تحديد الخصم',`<div class="actions">${[5,10,15,20].map(p=>`<button class="btn orange" onclick="applyDiscount(${p})">${p}%</button>`).join('')}</div><div class="form" style="margin-top:12px"><label>خصم بمبلغ<input id="dc" type="number"></label></div><button class="btn primary" style="margin-top:10px" onclick="state.discount=Math.min(sub(),Number(val('dc'))||0);closeModal();render()">تطبيق</button>`)}
function applyDiscount(p){state.discount=Math.round(sub()*p/100);closeModal();render()}
async function saveSale(){if(!state.cart.length)return toast('السلة فاضية');let x={id:uid(),date:now(),items:state.cart,subtotal:sub(),discount:state.discount,total:grand(),note:state.cartNote};await put('sales',x);await put('invoices',{id:uid(),date:x.date,type:'بيع',total:x.total,ref:x.id,note:x.note});await put('cash',{id:uid(),date:x.date,type:'in',amount:x.total,reason:'بيع',ref:x.id,note:x.note});let ps=await req('products');for(const i of state.cart){let p=ps.find(p=>p.id===i.id);if(p&&p.stock<100){p.stock=Math.max(0,p.stock-i.qty);await put('products',p)}}state.lastInvoice=x;clearCart();toast('تم حفظ البيع — الفاتورة جاهزة للطباعة');printInvoice(x)}
async function repair(v){let rs=await req('repairs');let groups={new:rs.filter(r=>r.status==='تحت الفحص'),ready:rs.filter(r=>r.status==='جاهز'),wait:rs.filter(r=>r.status==='بانتظار العميل'),done:rs.filter(r=>r.status==='تم التسليم')};const col=(title,a,action='')=>`<div class="stage"><h3>${title} (${a.length})</h3>${a.map(r=>`<div class="job"><b>${r.customer} • ${r.device}</b><small>${r.fault}</small><small>${r.phone||'بدون هاتف'}</small><div class="age">منذ ${Math.floor((Date.now()-new Date(r.date))/86400000)} يوم</div>${r.status!=='تم التسليم'?`<button class="btn mint" style="margin-top:8px" onclick="repairAction('${r.id}')">فتح الملف</button>`:''}</div>`).join('')||'<div class="empty">فارغ</div>'}</div>`;v.innerHTML=`<div class="section"><h2>لوحة الصيانة — بدون دفاتر</h2><button class="btn primary" onclick="newRepair()">＋ استلام جهاز</button></div><div class="pipeline">${col('تحت الفحص',groups.new)}${col('جاهز',groups.ready)}${col('بانتظار العميل',groups.wait)}${col('تم التسليم',groups.done)}</div>`}
function newRepair(){modal('استلام جهاز',`<div class="form"><label>اسم العميل<input id="rc"></label><label>الهاتف<input id="rp"></label><label>نوع الجهاز<select id="rd"><option>PS5</option><option>PS4</option><option>PS4 Pro</option><option>PS3</option><option>Xbox</option><option>أخرى</option></select></label><label>العطل<input id="rf" placeholder="HDMI / Power / بوردة..."></label><label class="full">ملاحظات الاستلام<textarea id="rn" placeholder="ملحقات الجهاز، حالته، أي شيء مهم..."></textarea></label></div><button class="btn primary" style="margin-top:11px" onclick="saveRepair()">حفظ الاستلام</button>`)}
async function saveRepair(){let x={id:uid(),date:now(),customer:val('rc'),phone:val('rp'),device:val('rd'),fault:val('rf'),note:val('rn'),status:'تحت الفحص'};if(!x.customer||!x.fault)return toast('الاسم والعطل مطلوبان');await put('repairs',x);await log('استلام صيانة',x);closeModal();toast('تم استلام الجهاز');render()}
async function repairAction(id){let r=(await req('repairs')).find(x=>x.id===id);modal('ملف الصيانة',`<div class="grid two"><div class="card"><b>${r.customer}</b><p>${r.device} — ${r.fault}</p><small>استلام: ${new Date(r.date).toLocaleString('ar-EG')}</small><p>${r.note||'لا توجد ملاحظات'}</p></div><div class="form"><label>الحالة<select id="rst"><option ${r.status==='تحت الفحص'?'selected':''}>تحت الفحص</option><option ${r.status==='جاهز'?'selected':''}>جاهز</option><option ${r.status==='بانتظار العميل'?'selected':''}>بانتظار العميل</option><option>تم التسليم</option></select></label><label>قيمة الصيانة<input id="ra" type="number" value="${r.amount||''}"></label><label class="full">ملاحظة<textarea id="rn2">${r.note||''}</textarea></label></div></div><div class="actions" style="margin-top:12px"><button class="btn primary" onclick="updateRepair('${id}')">حفظ الحالة</button></div>`)}
async function updateRepair(id){let r=(await req('repairs')).find(x=>x.id===id),old=r.status;r.status=val('rst');r.amount=Number(val('ra'))||0;r.note=val('rn2');if(r.status==='تم التسليم'&&old!=='تم التسليم'&&r.amount){await put('cash',{id:uid(),date:now(),type:'in',amount:r.amount,reason:'صيانة - '+r.customer,ref:r.id});await put('invoices',{id:uid(),date:now(),type:'صيانة',total:r.amount,ref:r.id})}await put('repairs',r);await log('تعديل صيانة',r);closeModal();toast('تم تحديث ملف الصيانة');render()}
async function inventory(v){let ps=await req('products');v.innerHTML=`<div class="section"><h2>المخزون — الكمية والقيمة والحد الأدنى</h2><button class="btn primary" onclick="productNew()">＋ منتج / خدمة</button></div><div class="grid stats">${stat('قيمة المخزون',ps.filter(p=>p.stock<100).reduce((a,p)=>a+p.cost*p.stock,0),'بسعر التكلفة')}${stat('عدد الأصناف',ps.length,'منتجات + خدمات')}${stat('تحت الحد الأدنى',ps.filter(p=>p.stock<=p.min&&p.min>0).length,'جاهز للشراء')}</div><div class="card table-wrap"><table class="table"><thead><tr><th>صورة</th><th>المنتج</th><th>القسم</th><th>التكلفة</th><th>البيع</th><th>هامش الوحدة</th><th>الموجود</th><th>حد أدنى</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${p.image?`<img src="${p.image}" style="width:45px;height:35px;object-fit:cover;border-radius:7px">`:p.emoji}</td><td><b>${p.name}</b><br><small>${p.note||''}</small></td><td>${p.cat}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td>${money(p.price-p.cost)}</td><td><span class="badge ${p.stock<=p.min?'redbg':'green'}">${p.stock>100?'خدمة':p.stock}</span></td><td>${p.min}</td></tr>`).join('')}</tbody></table></div>`}
function productNew(){modal('إضافة منتج / خدمة',`<div class="form"><label>اسم المنتج<input id="pn"></label><label>القسم<input id="pc" placeholder="أجهزة / دراعات / ألعاب / إكسسوارات / خدمات"></label><label>سعر البيع<input id="pp" type="number"></label><label>التكلفة علينا<input id="pk" type="number"></label><label>الكمية<input id="pq" type="number" value="1"></label><label>الحد الأدنى<input id="pm" type="number" value="1"></label><label>إيموجي<input id="pe" value="📦"></label><label>صورة<input id="pi" type="file" accept="image/*"></label><label class="full">ملاحظة<textarea id="pno"></textarea></label></div><button class="btn primary" style="margin-top:11px" onclick="saveProduct()">حفظ</button>`)}
function readFile(i){return new Promise(r=>{let f=$(i).files[0];if(!f)return r('');let x=new FileReader();x.onload=()=>r(x.result);x.readAsDataURL(f)})}
async function saveProduct(){let p={id:uid(),name:val('pn'),cat:val('pc')||'أخرى',price:Number(val('pp'))||0,cost:Number(val('pk'))||0,stock:Number(val('pq'))||0,min:Number(val('pm'))||0,emoji:val('pe')||'📦',image:await readFile('pi'),note:val('pno')};if(!p.name)return toast('اكتب اسم المنتج');await put('products',p);await log('إضافة منتج',p);closeModal();toast('تم حفظ المنتج');render()}
async function purchases(v){let ps=await req('products'),xs=await req('purchases');v.innerHTML=`<div class="section"><h2>المشتريات — البضاعة تدخل المخزون تلقائيًا</h2><button class="btn primary" onclick="purchaseNew()">＋ شراء بضاعة</button></div><div class="card"><div class="kpi"><span>قاعدة مهمة</span><b>ما سأبيعه للعميل = مشتريات / ما أستهلكه = مصروفات</b></div><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>الصنف</th><th>الكمية</th><th>التكلفة</th><th>الإجمالي</th><th>ملاحظة</th></tr></thead><tbody>${xs.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${new Date(x.date).toLocaleString('ar-EG')}</td><td>${x.product}</td><td>${x.qty}</td><td>${money(x.unitCost)}</td><td>${money(x.total)}</td><td>${x.note||''}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد مشتريات</td></tr>'}</tbody></table></div></div>`}
async function purchaseNew(){let ps=await req('products');modal('شراء بضاعة',`<div class="form"><label>الصنف<select id="bp">${ps.filter(p=>p.stock<100).map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></label><label>الكمية<input id="bq" type="number" value="1"></label><label>تكلفة الوحدة<input id="bc" type="number"></label><label class="full">ملاحظة<textarea id="bn" placeholder="مثال: شراء PS3 مستعمل من مورد..."></textarea></label></div><button class="btn primary" style="margin-top:11px" onclick="savePurchase()">حفظ</button>`)}
async function savePurchase(){let ps=await req('products'),p=ps.find(x=>x.id===val('bp')),q=Number(val('bq'))||1,c=Number(val('bc'))||p.cost,total=q*c;if(!p)return toast('اختار صنف');p.stock+=q;p.cost=c;await put('products',p);let x={id:uid(),date:now(),product:p.name,productId:p.id,qty:q,unitCost:c,total,note:val('bn')};await put('purchases',x);await put('cash',{id:uid(),date:x.date,type:'out',amount:total,reason:'شراء بضاعة - '+p.name,ref:x.id,note:x.note});await log('شراء بضاعة',x);closeModal();toast('تمت الزيادة في المخزون وتسجيل الخرج');render()}
async function cash(v){let xs=await req('cash'),d=today(),td=xs.filter(x=>x.date.slice(0,10)===d),inc=td.filter(x=>x.type==='in').reduce((a,x)=>a+x.amount,0),out=td.filter(x=>x.type==='out').reduce((a,x)=>a+x.amount,0);v.innerHTML=`<div class="grid stats">${stat('دخل اليوم',inc,'')}${stat('خرج اليوم',out,'')}${stat('صافي الدرج',inc-out,'قبل العد')}${stat('حركات اليوم',td.length,'')}</div><div class="section"><h2>دفتر الدخل والخرج</h2><div class="actions"><button class="btn mint" onclick="cashNew('in')">＋ دخل</button><button class="btn red" onclick="cashNew('out')">＋ خرج</button></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>الوقت</th><th>النوع</th><th>البيان</th><th>دخل</th><th>خرج</th><th>ملاحظة</th></tr></thead><tbody>${xs.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${new Date(x.date).toLocaleString('ar-EG')}</td><td>${x.type==='in'?'داخل':'خارج'}</td><td>${x.reason}</td><td>${x.type==='in'?money(x.amount):'—'}</td><td>${x.type==='out'?money(x.amount):'—'}</td><td>${x.note||''}</td></tr>`).join('')}</tbody></table></div>`}
function cashNew(type){let opts=type==='in'?['دخل آخر','تحصيل','عربون','استرداد من مورد','أخرى']:['سلفة موظف','إيجار','كهرباء','مياه','معطر واستهلاك','نقل','أخرى'];modal(type==='in'?'دخل جديد':'خرج جديد',`<div class="form"><label>المبلغ<input id="ca" type="number"></label><label>البيان<select id="cr">${opts.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="full">ملاحظة<textarea id="cn"></textarea></label></div><button class="btn ${type==='in'?'mint':'red'}" style="margin-top:11px" onclick="saveCash('${type}')">حفظ</button>`)}
async function saveCash(type){let a=Number(val('ca'))||0;if(!a)return toast('اكتب المبلغ');let x={id:uid(),date:now(),type,amount:a,reason:val('cr'),note:val('cn')};await put('cash',x);await log('حركة خزنة',x);closeModal();toast('تم حفظ الحركة');render()}
async function expenses(v){let xs=await req('expenses');v.innerHTML=`<div class="section"><h2>مصروفات التشغيل — ليست بضاعة للبيع</h2><button class="btn red" onclick="expenseNew()">＋ مصروف</button></div><div class="card"><div class="grid four"><div class="card"><b>إيجار</b><small>تشغيل</small></div><div class="card"><b>كهرباء / مياه</b><small>تشغيل</small></div><div class="card"><b>معطر / تنظيف</b><small>استهلاك</small></div><div class="card"><b>نقل / أخرى</b><small>تشغيل</small></div></div><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>النوع</th><th>المبلغ</th><th>ملاحظة</th></tr></thead><tbody>${xs.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${new Date(x.date).toLocaleString('ar-EG')}</td><td>${x.type}</td><td>${money(x.amount)}</td><td>${x.note||''}</td></tr>`).join('')}</tbody></table></div></div>`}
function expenseNew(){modal('مصروف تشغيل',`<div class="form"><label>النوع<select id="et"><option>إيجار</option><option>كهرباء</option><option>مياه</option><option>إنترنت</option><option>معطر / تنظيف</option><option>نقل</option><option>أخرى</option></select></label><label>المبلغ<input id="ea" type="number"></label><label class="full">ملاحظة<textarea id="en"></textarea></label></div><button class="btn red" style="margin-top:11px" onclick="saveExpense()">حفظ</button>`)}
async function saveExpense(){let a=Number(val('ea'))||0,x={id:uid(),date:now(),type:val('et'),amount:a,note:val('en')};await put('expenses',x);await put('cash',{id:uid(),date:x.date,type:'out',amount:a,reason:x.type,ref:x.id,note:x.note});await log('مصروف',x);closeModal();toast('تم تسجيل المصروف');render()}
async function staff(v){let xs=await req('staff'),cashx=await req('cash');v.innerHTML=`<div class="section"><h2>الفنيون والموظفون — السلف والمستحقات</h2><button class="btn primary" onclick="staffNew()">＋ موظف / فني</button></div><div class="card"><p style="color:var(--muted)">هنا نسجل الأشخاص العاملين وسلفهم. السلفة تظهر تلقائيًا كخرج من الخزنة، بدل ما تختلط بالمشتريات أو مصروفات المحل.</p><div class="table-wrap"><table class="table"><thead><tr><th>الاسم</th><th>الدور</th><th>السلف</th><th>ملاحظات</th><th></th></tr></thead><tbody>${xs.map(x=>{let adv=cashx.filter(c=>c.type==='out'&&c.reason==='سلفة موظف'&&c.staffId===x.id).reduce((a,c)=>a+c.amount,0);return `<tr><td><b>${x.name}</b></td><td>${x.role}</td><td>${money(adv)}</td><td>${x.note||''}</td><td><button class="btn orange" onclick="advance('${x.id}')">سلفة</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">أضف الفنيين والموظفين عند الحاجة</td></tr>'}</tbody></table></div></div>`}
function staffNew(){modal('إضافة فني / موظف',`<div class="form"><label>الاسم<input id="sn"></label><label>الدور<input id="sr" placeholder="فني / موظف / إداري"></label><label class="full">ملاحظة<textarea id="sno"></textarea></label></div><button class="btn primary" style="margin-top:11px" onclick="saveStaff()">حفظ</button>`)}
async function saveStaff(){let x={id:uid(),name:val('sn'),role:val('sr'),note:val('sno')};await put('staff',x);closeModal();toast('تم إضافة الشخص');render()}
async function advance(id){let s=(await req('staff')).find(x=>x.id===id);modal('سلفة — '+s.name,`<div class="form"><label>المبلغ<input id="ava" type="number"></label><label class="full">ملاحظة<textarea id="avn"></textarea></label></div><button class="btn red" style="margin-top:11px" onclick="saveAdvance('${id}')">تسجيل السلفة</button>`)}
async function saveAdvance(id){let a=Number(val('ava'))||0;if(!a)return toast('اكتب المبلغ');await put('cash',{id:uid(),date:now(),type:'out',amount:a,reason:'سلفة موظف',staffId:id,note:val('avn')});closeModal();toast('تم تسجيل السلفة كخرج من الخزنة');render()}
async function customers(v){let xs=await req('customers');v.innerHTML=`<div class="section"><h2>العملاء والخصومات الذكية</h2><button class="btn primary" onclick="customerNew()">＋ عميل</button></div><div class="card"><p style="color:var(--muted)">احفظ العميل الدائم وملاحظته، ثم استخدم قرار الخصم في كل فاتورة بدل خصم عشوائي.</p><div class="table-wrap"><table class="table"><thead><tr><th>الاسم</th><th>الهاتف</th><th>ملاحظات</th><th>تاريخ الإضافة</th></tr></thead><tbody>${xs.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.phone||''}</td><td>${x.note||''}</td><td>${new Date(x.date).toLocaleDateString('ar-EG')}</td></tr>`).join('')}</tbody></table></div></div>`}
function customerNew(){modal('عميل جديد',`<div class="form"><label>الاسم<input id="cname"></label><label>الهاتف<input id="cphone"></label><label class="full">ملاحظة<textarea id="cnote" placeholder="دائم / يفضل خصم / ملاحظة خدمة..."></textarea></label></div><button class="btn primary" style="margin-top:11px" onclick="saveCustomer()">حفظ</button>`)}
async function saveCustomer(){let x={id:uid(),date:now(),name:val('cname'),phone:val('cphone'),note:val('cnote')};if(!x.name)return toast('اكتب اسم العميل');await put('customers',x);closeModal();toast('تم حفظ العميل');render()}
async function needs(v){let ps=await req('products'),low=ps.filter(p=>p.stock<=p.min&&p.min>0);v.innerHTML=`<div class="section"><h2>قائمة الاحتياجات — النظام يرشحها لك</h2><button class="btn primary" onclick="state.page='purchases';render()">فتح المشتريات</button></div><div class="card">${low.map(p=>`<div class="kpi"><span>📦 <b>${p.name}</b><small> — الموجود ${p.stock} / الحد ${p.min}</small></span><button class="btn orange" onclick="toast('تم تمييز ${p.name} كاحتياج')">مطلوب</button></div>`).join('')||'<div class="empty">مفيش أصناف تحت الحد الأدنى 🎉</div>'}</div>`}
async function reports(v){let [s,r,e,c,days]=await Promise.all([req('sales'),req('repairs'),req('expenses'),req('cash'),req('days')]),d=today(),td=c.filter(x=>x.date.slice(0,10)===d),sd=s.filter(x=>x.date.slice(0,10)===d),rd=r.filter(x=>x.date.slice(0,10)===d&&x.status==='تم التسليم'),ed=e.filter(x=>x.date.slice(0,10)===d),inc=td.filter(x=>x.type==='in').reduce((a,x)=>a+x.amount,0),out=td.filter(x=>x.type==='out').reduce((a,x)=>a+x.amount,0),sales=sd.reduce((a,x)=>a+x.total,0),cogs=sd.reduce((a,x)=>a+x.items.reduce((z,i)=>z+i.cost*i.qty,0),0),repIncome=rd.reduce((a,x)=>a+(x.amount||0),0),op=ed.reduce((a,x)=>a+x.amount,0),profit=sales+repIncome-cogs-op,closed=days.find(x=>x.date===d);v.innerHTML=`<div class="grid stats">${stat('المبيعات',sales,'بعد الخصم')}${stat('تكلفة البضاعة',cogs,'تكلفة الأصناف المباعة')}${stat('دخل الصيانة',repIncome,'المسلّم اليوم')}${stat('مصروفات التشغيل',op,'بدون المشتريات')}${stat('الربح التقريبي',profit,'بعد التكلفة والمصروفات')}${stat('فرق الدرج',closed?closed.difference:'—',closed?'تم الإقفال':'لم يُغلق')}</div><div class="section"><h2>🔒 إقفال اليوم</h2><button class="btn primary" onclick="closeDay()">عدّ الدرج وإقفال اليوم</button></div><div class="card close-box"><div class="grid three"><div><small>دخل مسجل</small><div class="expected">${money(inc)}</div></div><div><small>خرج مسجل</small><div class="expected">${money(out)}</div></div><div><small>المتوقع في الدرج</small><div class="expected">${money(inc-out)}</div></div></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><b>${closed?'اليوم مقفول بالفعل.':'قبل الإقفال راجع الصيانة والمبيعات والمصروفات والاحتياجات.'}</b></div><div class="section"><h2>تحليل سريع</h2></div><div class="grid two"><div class="card"><div class="kpi"><span>عدد عمليات البيع</span><b>${sd.length}</b></div><div class="kpi"><span>خصومات اليوم</span><b>${money(sd.reduce((a,x)=>a+x.discount,0))}</b></div><div class="kpi"><span>أجهزة تم تسليمها</span><b>${rd.length}</b></div></div><div class="card"><div class="kpi"><span>قيمة المبيعات قبل التكلفة</span><b>${money(sales+repIncome)}</b></div><div class="kpi"><span>تكلفة البضاعة</span><b>${money(cogs)}</b></div><div class="kpi"><span>هامش تقريبي</span><b class="${profit>=0?'positive':'negative'}">${money(profit)}</b></div></div></div>`}
async function closeDay(){let [c,days]=await Promise.all([req('cash'),req('days')]),d=today(),td=c.filter(x=>x.date.slice(0,10)===d),expected=td.filter(x=>x.type==='in').reduce((a,x)=>a+x.amount,0)-td.filter(x=>x.type==='out').reduce((a,x)=>a+x.amount,0),old=days.find(x=>x.date===d);modal('إقفال اليوم — عد فلوس الدرج',`<div class="card"><small>المتوقع حسب النظام</small><div class="expected">${money(expected)}</div><p style="color:var(--muted)">المتوقع = كل الداخل المسجل − كل الخارج المسجل اليوم.</p></div><div class="form" style="margin-top:11px"><label>الفلوس الفعلية في الدرج<input id="count" type="number" value="${old?.counted??''}"></label><label class="full">ملاحظة الإقفال<textarea id="dn">${old?.note||''}</textarea></label></div><div id="difference" style="margin-top:10px"></div><button class="btn primary" style="margin-top:10px" onclick="saveDay(${expected},'${d}')">حفظ الإقفال</button>`);$('count').oninput=e=>{$('difference').innerHTML=`<div class="diff ${(Number(e.target.value)||0)-expected===0?'positive':'negative'}">${((Number(e.target.value)||0)-expected)===0?'✅ الدرج مطابق':`⚠ الفرق: ${money((Number(e.target.value)||0)-expected)}`}</div>`}}
async function saveDay(expected,d){let counted=Number(val('count'))||0;await put('days',{id:d,date:d,expected,counted,difference:counted-expected,note:val('dn'),closedAt:now()});closeModal();toast('تم إقفال اليوم وحفظ الفرق');render()}
async function invoices(v){let xs=await req('invoices');v.innerHTML=`<div class="section"><h2>الفواتير</h2></div><div class="card table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>النوع</th><th>الإجمالي</th><th>ملاحظة</th><th></th></tr></thead><tbody>${xs.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${new Date(x.date).toLocaleString('ar-EG')}</td><td>${x.type}</td><td>${money(x.total)}</td><td>${x.note||''}</td><td>${x.type==='بيع'?`<button class="btn" onclick="reprint('${x.ref}')">طباعة</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">لا توجد فواتير</td></tr>'}</tbody></table></div>`}
async function reprint(ref){let x=(await req('sales')).find(s=>s.id===ref);if(x)printInvoice(x)}
function printInvoice(x){let items=x.items.map(i=>`<tr><td>${i.name}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.price*i.qty)}</td></tr>`).join('');let w=window.open('','_blank');if(!w)return toast('المتصفح منع نافذة الطباعة');w.document.write(`<html dir="rtl"><head><title>فاتورة MAGHRABY STORE</title><style>body{font-family:Arial;padding:25px;color:#102a43}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:right}.total{font-size:22px;font-weight:bold;margin-top:20px}.note{margin-top:15px;background:#f4f7f8;padding:10px}</style></head><body><h1>MAGHRABY STORE</h1><p>${new Date(x.date).toLocaleString('ar-EG')}</p><table><tr><th>الصنف</th><th>العدد</th><th>السعر</th><th>الإجمالي</th></tr>${items}</table><p>قبل الخصم: ${money(x.subtotal)}</p><p>الخصم: ${money(x.discount)}</p><div class="total">الإجمالي: ${money(x.total)}</div><div class="note">${x.note||''}</div><script>window.print()<\/script></body></html>`);w.document.close()}
async function settings(v){v.innerHTML=`<div class="grid two"><div class="card"><h2>💾 البيانات</h2><p>البرنامج Offline-First: البيانات الأساسية تحفظ داخل المتصفح على الجهاز، وليس في GitHub.</p><div class="actions"><button class="btn primary" onclick="backup()">تصدير نسخة احتياطية</button><label class="btn">استيراد<input type="file" hidden accept=".json" onchange="restore(this.files[0])"></label></div></div><div class="card"><h2>🖨 الفواتير</h2><p>الفاتورة تفتح في نافذة طباعة عادية الآن، ويمكن لاحقًا ربطها بطابعة حرارية مباشرة.</p></div><div class="card"><h2>🎨 الهوية</h2><p>ضع اللوجو الحقيقي في <b>public/logo.svg</b>. كل الواجهة مبنية على ألوان وهوية منفصلة عن الوظائف لتسهيل تعديلها.</p></div><div class="card"><h2>🧠 منطق النظام</h2><p>المبيعات تقلل المخزون، المشتريات تزيده، تكلفة البضاعة تدخل في حساب الربح، المصروفات التشغيلية منفصلة، والسلف تخرج من الخزنة وتظهر على الموظف.</p></div></div>`}
async function backup(){let data={version:3,exportedAt:now()};for(const s of stores)data[s]=await req(s);let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download='MAGHRABY_STORE_BACKUP_'+today()+'.json';a.click();toast('تم إنشاء النسخة الاحتياطية')}
async function restore(file){if(!file)return;try{let d=JSON.parse(await file.text());for(const s of stores)for(const x of (d[s]||[]))await put(s,x);toast('تم استرجاع البيانات');render()}catch(e){toast('ملف النسخة غير صالح')}}
async function log(action,data){await put('audit',{id:uid(),date:now(),action,data})}
function modal(t,b){$('mt').textContent=t;$('mb').innerHTML=b;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}$('mc').onclick=closeModal;
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;$('toast').appendChild(x);setTimeout(()=>x.remove(),2300)}
boot();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});